// Este script se ejecuta cuando MongoDB arranca por primera vez
db = db.getSiblingDB("licitalab");

// Crear colecciones
db.createCollection("opportunities");
db.createCollection("users");
db.createCollection("userFollowings");
db.createCollection("categories");
db.createCollection("companies");
db.createCollection("notifications");

db.opportunities.insertMany([
  {
    code: "L1-01-25",
    title: "Adquisición de computadores",
    type: "tender",
    is_followed: true,
    publish_date: new Date("2025-03-20T08:00:00Z"),
    close_date: new Date("2025-03-25T08:00:00Z"),
    description: "Compra de equipos informáticos para oficinas",
    budget: 50000,
    requirements: ["Garantía 3 años", "Soporte técnico"],
    status: "published",
    categories: ["tecnología", "hardware"],
    attachments: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    code: "L1-02-25",
    title: "Desarrollo de software empresarial",
    type: "agile",
    is_followed: false,
    publish_date: new Date("2025-03-25T09:00:00Z"),
    close_date: new Date("2025-04-15T09:00:00Z"),
    description: "Implementación de sistema de gestión empresarial",
    budget: 100000,
    requirements: ["Metodología Agile", "Documentación completa"],
    status: "published",
    categories: ["tecnología", "software"],
    attachments: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    code: "L1-03-25",
    title: "Suministro de mobiliario de oficina",
    type: "tender",
    is_followed: true,
    publish_date: new Date("2025-02-18T10:00:00Z"),
    close_date: new Date("2025-03-11T10:00:00Z"),
    description: "Compra de mobiliario para nuevas oficinas",
    budget: 75000,
    requirements: ["Certificaciones de calidad", "Entrega e instalación"],
    status: "published",
    categories: ["infraestructura"],
    attachments: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    code: "L1-04-25",
    title: "Implementación de red de fibra óptica",
    type: "agile",
    is_followed: false,
    publish_date: new Date("2025-03-28T11:00:00Z"),
    close_date: new Date("2025-04-11T11:00:00Z"),
    description: "Modernización de infraestructura de red",
    budget: 200000,
    requirements: ["Alta disponibilidad", "Soporte 24/7"],
    status: "published",
    categories: ["tecnología", "infraestructura"],
    attachments: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    code: "L1-05-25",
    title: "Mantenimiento de equipos industriales",
    type: "tender",
    is_followed: true,
    publish_date: new Date("2025-02-01T12:00:00Z"),
    close_date: new Date("2025-03-10T12:00:00Z"),
    description: "Servicio de mantenimiento preventivo y correctivo",
    budget: 50000,
    requirements: ["Certificaciones técnicas", "Personal especializado"],
    status: "published",
    categories: ["mantenimiento"],
    attachments: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    code: "L1-06-25",
    title: "Construcción de edificio corporativo",
    type: "tender",
    is_followed: false,
    publish_date: new Date("2025-01-16T13:00:00Z"),
    close_date: new Date("2025-01-20T13:00:00Z"),
    description: "Proyecto de construcción de nuevo edificio corporativo",
    budget: 5000000,
    requirements: ["Planos aprobados", "Estudios de impacto ambiental"],
    status: "published",
    categories: ["construcción"],
    attachments: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    code: "L1-07-25",
    title: "Adquisición de servidores y almacenamiento",
    type: "agile",
    is_followed: true,
    publish_date: new Date("2025-03-28T14:00:00Z"),
    close_date: new Date("2025-04-11T14:00:00Z"),
    description: "Mejora de infraestructura de servidores",
    budget: 150000,
    requirements: ["Alta capacidad", "Tecnología de última generación"],
    status: "published",
    categories: ["tecnología", "hardware"],
    attachments: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    code: "L1-08-25",
    title: "Consultoría en transformación digital",
    type: "tender",
    is_followed: false,
    publish_date: new Date("2025-03-28T15:00:00Z"),
    close_date: new Date("2025-04-11T15:00:00Z"),
    description: "Estrategia de transformación digital empresarial",
    budget: 100000,
    requirements: ["Experiencia comprobada", "Metodología innovadora"],
    status: "published",
    categories: ["consultoría", "tecnología"],
    attachments: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    code: "L1-09-25",
    title: "Servicios de ciberseguridad",
    type: "agile",
    is_followed: true,
    publish_date: new Date("2025-03-28T16:00:00Z"),
    close_date: new Date("2025-04-11T16:00:00Z"),
    description: "Evaluación y mejora de sistemas de seguridad",
    budget: 80000,
    requirements: [
      "Certificaciones de seguridad",
      "Análisis de vulnerabilidades",
    ],
    status: "published",
    categories: ["tecnología", "seguridad"],
    attachments: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    code: "L1-10-25",
    title: "Implementación de ERP empresarial",
    type: "tender",
    is_followed: false,
    publish_date: new Date("2025-03-28T17:00:00Z"),
    close_date: new Date("2025-04-11T17:00:00Z"),
    description: "Sistema integral de gestión empresarial",
    budget: 250000,
    requirements: ["Personalización", "Capacitación incluida"],
    status: "published",
    categories: ["tecnología", "software"],
    attachments: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]);

// Insertar categorías
db.categories.insertMany([
  {
    name: "Tecnología",
    description: "Productos y servicios tecnológicos",
    parentCategory: null,
  },
  {
    name: "Hardware",
    description: "Equipos físicos",
    parentCategory: "Tecnología",
  },
  {
    name: "Software",
    description: "Programas y aplicaciones",
    parentCategory: "Tecnología",
  },
  {
    name: "Consultoría",
    description: "Servicios de asesoría",
    parentCategory: null,
  },
  {
    name: "Construcción",
    description: "Servicios de construcción",
    parentCategory: null,
  },
]);

// Insertar una empresa inicial
db.companies.insertMany([
  {
    name: "LicitaLAB",
    type: "government",
    contact: { email: "info@licitalab.cl", phone: "123456789" },
    opportunities: [],
  },
]);

// Crear usuario administrador inicial
db.users.insertOne({
  username: "admin",
  email: "admin@licitalab.cl",
  password: "$2b$10$X/tE9.EPuP.jA2iRYQ8Lx.VKl8E2SQ40ZnTnaaPSQOTJl9x2FyRkS", // "admin123" encriptado
  role: "admin",
  fullName: "Administrador",
  company: "LicitaLAB",
  createdAt: new Date(),
  lastLogin: null,
});
